# https://github.com/vvatelot/mosquitto-docker-compose

volumes:
  mosquitto:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_mosquitto

services:
  mosquitto:
    restart: always
    image: eclipse-mosquitto:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/password.txt:/mosquitto/config/password.txt
      - ./mosquitto/logs:/mosquitto/log
      - mosquitto:/mosquitto/data
    network_mode: host
